using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace Mineral_Management.Data.Models
{
    public class Product
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public string ProductId { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string ImageSource { get; set; }

        public string ImageName { get; set; } 

        public Minerals Minerals { get; set; }

        public string products { get; set; } = "product";

        public string UserId { get; set; }
    }
}
